# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58bf03b8d4b654f4a64e3acc6e232aade96a03cc26ada25b86a3ba487871b649884e0e2527472beae77b845b3b5df247f408eb07c296305e23e057fc3ef91cd1

test:
  secret_key_base: bf0f0041389468e6e945a8785f96513937207bf4d3b9ccf466a889a583751f742b71185e06beec79d3aa06664bff072a36e80b4116ec15b32899480abe3453cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
